config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'articles/index'
  root 'welcome#index'
  resources :articles do
    resources :comments
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	  has_many :comments, dependent: :destroy
	 validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def new
    @article =Article.new

  end

  def edit
    @article = Article.find(params[:id])  
  end

  def create
  @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
   
    redirect_to articles_path
  end


  private
  def article_params
    params.require(:article).permit(:title, :text)
  end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	# http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

	def index 
		@comments = Comment.all
	end

	def create
	    @article = Article.find(params[:article_id])
	    @comment = @article.comments.create(comment_params)
	    redirect_to article_path(@article)
	end
	def destroy
	    @article = Article.find(params[:article_id])
	    @comment = @article.comments.find(params[:id])
	    @comment.destroy
	    redirect_to article_path(@article)
	  end
	 
	private
	   def comment_params
	    params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<link rel="stylesheet" href="articles.css">
<div class= "form-container">
<%= form_with model: @article, local: true, class: 'background-form' do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2> 
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-8">
    <%= form.label :title, class: "control-label" %><br>
    <%= form.text_field :title ,class: "form-control" %>
  </div>
 
  <div class="col-md-8">
    <%= form.label :text, class:"control-label" %><br>
    <%= form.text_area :text, class:"form-control" %>
  </div>
 <br>
  <div>
    <%= form.submit class: 'btn btn-outline-success' %>
  </div><br>
  <%= link_to 'Back', articles_path , class: "btn btn-outline-primary"   %> 
<% end %>
</div>

app/views/articles/edit.html.erb
<marquee><h1>Edit article</h1></marquee>
 
<%= render 'form' %>
 

app/views/articles/index.html.erb
<html style=  "background-image: url(/assets/wallpaper.jpg");alt="smiley face">
<head>
<marquee>hello rails</marquee>

<h1>Listing articles</h1>
<%= link_to 'All welcome recode', welcome_index_path, class: 'btn btn-primary' %>
<%= link_to 'new article', new_article_path , class: "btn btn-primary" %>
</head>
<body>
<table class="table table-bordered">
  <thead class="thead-dark">
  <tr>
  	<th>ID</th>
    <th>Title</th>
    <th>Text</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Destory</th>
  </tr>
</thead>
 <tbody>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.id %></td>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article), class: 'btn btn-primary' %>
      </td>
      <td><%= link_to 'Edit', edit_article_path(article) ,class:'btn btn-success' %></td>
      <td><%= link_to 'Destroy', article_path(article), class: 'btn btn-danger',
            method: :delete,
            data: { confirm: 'Are you sure?' } %>
       </button></td>
    </tr>
  <% end %>
</tbody>
</table>
</body>
</html>

app/views/articles/new.html.erb
<marquee><h1>New article</h1></marquee> 
<%= render 'form' %>

app/views/articles/show.html.erb
<html>
<head>
	
</head>
<body >
<p>
<strong>Title:</strong>
<%= @article.title %>
</p>

<p>
<strong>Text:</strong>
<%= @article.text %>
</p>


<h2>Comments</h2>
<%= render @article.comments%>
<h2>Add a comment:</h2>
<%= render 'comments/form' %>


</body>
</html>

app/views/comments/_comment.html.erb
<p>
  <strong>ID :</strong>
  <%= comment.id %>
</p>

<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<p>
    <%= link_to 'Destroy Comment', [comment.article, comment],class: 'btn btn-outline-primary',
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<link rel="stylesheet" href="articles.css">

<div class="form-container">

<%= form_with(model: [ @article, @article.comments.build ], local: true , class: 'background-form' ) do |form| %>
  <div class="col-md-8">
    <%= form.label :commenter, class: "control-label" %>
    <%= form.text_field :commenter, class: "form-control" %>
  </div>
  <div class="col-md-8">
    <%= form.label :body , class:"control-label" %><br>
    <%= form.text_area :body , class:"form-control" %>
  </div><br>
  <div>
    <%= form.submit class: 'btn btn-outline-success' %>
  </div><br>
  <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-success"  %> |
<%= link_to 'Back', articles_path , class: 'btn btn-outline-primary' %>

<% end %>

</div>

app/views/comments/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Add a comment:</h2>
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
 
<%= link_to 'Edit', edit_article_path(@article), %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogGuides</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<marquee><h1>Hello, Rails it's welcome page  !</h1></marquee>



<%= link_to 'All Articles recode ',articles_path, class: "btn btn-outline-primary" %>

<%= image_tag "wallpaper.jpg", alt: "Girl in a jacket" , class: "custom-image"%><br>